In [1]:
import torch

In [8]:
jacc_features = torch.Tensor([[0.5], [0.4], [0.1]])
threshold = 0.2
a

tensor([[0.5000],
        [0.4000],
        [0.1000]])

In [14]:
torch.mul( torch.floor( ( torch.sign(jacc_features - threshold)+1.0) / 2.0 ), jacc_features )

tensor([[0.5000],
        [0.4000],
        [0.0000]])

In [16]:
a = torch.Tensor([[-2.4877e-41],
        [ 1.1065e-09],
        [ 0.0000e+00],
        [ 1.7509e-21],
        [ 0.0000e+00],
        [ 0.0000e+00],
        [ 0.0000e+00],
        [ 1.9690e-06],
        [ 0.0000e+00],
        [ 1.6707e-15],
        [ 0.0000e+00],
        [ 2.6540e-25],
        [-1.1854e-39],
        [ 3.9624e-06],
        [ 0.0000e+00],
        [ 1.4878e-17],
        [-1.0118e-14],
        [ 3.9206e-14],
        [ 0.0000e+00],
        [ 2.5238e-22],
        [ 0.0000e+00],
        [ 1.2006e-03],
        [-2.9248e-16],
        [ 1.3972e-06],
        [ 0.0000e+00],
        [ 1.5014e-17],
        [ 0.0000e+00],
        [ 1.6665e-23],
        [-1.4952e-17],
        [ 1.5208e-06],
        [ 0.0000e+00],
        [ 1.0632e-06],
        [ 0.0000e+00],
        [ 2.8194e-07],
        [ 0.0000e+00],
        [ 3.6251e-22],
        [-4.6488e-04],
        [ 1.2210e-06],
        [ 0.0000e+00],
        [ 8.9633e-32],
        [ 0.0000e+00],
        [ 3.6415e-17],
        [-4.1997e-19],
        [ 8.0116e-38],
        [ 0.0000e+00],
        [ 5.2410e-07],
        [ 0.0000e+00],
        [ 4.1708e-06],
        [ 0.0000e+00],
        [ 1.0778e-30],
        [ 0.0000e+00],
        [ 3.5776e-31],
        [ 0.0000e+00],
        [ 2.6749e-03],
        [ 0.0000e+00],
        [ 6.6734e-19],
        [-2.9273e-28],
        [ 0.0000e+00],
        [ 0.0000e+00],
        [ 0.0000e+00],
        [ 0.0000e+00],
        [ 0.0000e+00],
        [ 0.0000e+00],
        [ 1.5475e-25]])

In [18]:
a.shape

torch.Size([64, 1])

In [18]:
import re
import pandas as pd

with open("output.txt") as f:
    lines = f.readlines()

rows = []
columns = ['model', 'binary', 'alpha', 'precision', 'recall', 'f1']
for line in lines:
    items = line.split('; ')
    items = [item.split('=')[-1].strip() for item in items]
    for i in range(2, 6):
        items[i] = float(items[i])
    print(items)
    rows.append(items)

print(rows)
df = pd.DataFrame(rows, columns=columns)
df.to_csv("output.csv")

['purename', 'False', 0.85, 0.8015, 0.7569, 0.7786]
['context', 'False', 0.85, 0.7887, 0.7442, 0.7658]
['complex', 'False', 0.85, 0.8079, 0.7633, 0.7849]
['purename', 'False', 0.9, 0.7983, 0.7537, 0.7754]
['context', 'False', 0.9, 0.7887, 0.7442, 0.7658]
['complex', 'False', 0.9, 0.7856, 0.741, 0.7626]
['purename', 'False', 0.95, 0.7856, 0.741, 0.7626]
['context', 'False', 0.95, 0.7665, 0.7282, 0.7469]
['complex', 'False', 0.95, 0.2197, 0.1911, 0.2044]
[['purename', 'False', 0.85, 0.8015, 0.7569, 0.7786], ['context', 'False', 0.85, 0.7887, 0.7442, 0.7658], ['complex', 'False', 0.85, 0.8079, 0.7633, 0.7849], ['purename', 'False', 0.9, 0.7983, 0.7537, 0.7754], ['context', 'False', 0.9, 0.7887, 0.7442, 0.7658], ['complex', 'False', 0.9, 0.7856, 0.741, 0.7626], ['purename', 'False', 0.95, 0.7856, 0.741, 0.7626], ['context', 'False', 0.95, 0.7665, 0.7282, 0.7469], ['complex', 'False', 0.95, 0.2197, 0.1911, 0.2044]]


## form tables

In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv("output/complex_nway_alpha085.csv")
df1 = df1[['Question', 'Entities', 'Classes']]
print(df1.shape)
df1.head()

(157, 3)


Question  \
0        Who was the wife of U.S. president Lincoln?   
1  How many people live in the capital of Australia?   
2  How many theories did Albert Einstein come up ...   
3  Who composed the soundtrack for Cameron's Tita...   
4                  Give me the runtime of Toy Story.   

                                            Entities Classes  
0  [[('http://dbpedia.org/resource/United_States'...      []  
1  [[('http://dbpedia.org/resource/Australia', 1....      []  
2  [[('http://dbpedia.org/resource/Albert_Einstei...      []  
3  [[('http://dbpedia.org/resource/David_Cameron'...      []  
4  [[('http://dbpedia.org/resource/Toy_Story_3', ...      []

In [3]:
df_missing = pd.read_csv("data/missing.csv", header=None)

In [4]:
df_missing.columns = ['Unnamed:0', 'Question', 'Entities', 'Classes']
df_missing = df_missing[['Question', 'Entities', 'Classes']]
df_missing.head()

Question Entities Classes
0             Which species does an elephant belong?       []      []
1  In which ancient empire could you pay with coc...       []      []
2               Which city has the most inhabitants?       []      []
3                What is in a chocolate chip cookie?       []      []
4    Which holidays are celebrated around the world?       []      []

In [58]:
pd.concat([df1, df_missing], ignore_index=True)

Question  \
0          Who was the wife of U.S. president Lincoln?   
1    How many people live in the capital of Australia?   
2    How many theories did Albert Einstein come up ...   
3    Who composed the soundtrack for Cameron's Tita...   
4                    Give me the runtime of Toy Story.   
..                                                 ...   
152  List all episodes of the first season of the H...   
153              Which city has the least inhabitants?   
154                           Is proinsulin a protein?   
155           Which city has the oldest running metro?   
156          What is the bridge with the longest span?   

                                              Entities Classes  
0    [[('http://dbpedia.org/resource/United_States'...      []  
1    [[('http://dbpedia.org/resource/Australia', 1....      []  
2    [[('http://dbpedia.org/resource/Albert_Einstei...      []  
3    [[('http://dbpedia.org/resource/David_Cameron'...      []  
4    [[('http://dbpedia.org/resource/Toy_Story', 1....      []  
..                                                 ...     ...  
152                                                 []      []  
153                                                 []      []  
154                                                 []      []  
155                                                 []      []  
156                                                 []      []  

[157 rows x 3 columns]

In [9]:
import argparse
from collections import defaultdict
import sys
sys.path.append('../../../')
from el_evaluation import *

parser = argparse.ArgumentParser(description="main training script for training lnn entity linking models")
parser.add_argument("--train_data", type=str, default="./data/train.csv", help="train csv")
parser.add_argument("--test_data", type=str, default="./data/test.csv", help="test csv")
parser.add_argument("--checkpoint_name", type=str, default="checkpoint/best_model.pt", help="checkpoint path")
parser.add_argument("--output_file_name", type=str, default="output/purename_nway_alpha09.txt", help="checkpoint path")
parser.add_argument("--model_name", type=str, default="purename", help="which model we choose")
# args for dividing the corpus
parser.add_argument('--alpha', type=float, default=0.9, help='alpha for LNN')
parser.add_argument('--num_epoch', type=int, default=100, help='training epochs for LNN')
parser.add_argument("--use_binary", action="store_true", help="default is to use binary`, otherwise use stem")
parser.add_argument("-f")
args = parser.parse_args()

if args.use_binary:
    from RuleLNN_binary import *
else:
    from RuleLNN_nway_theta import *

In [8]:
a = torch.Tensor([[1, 1, 1], [2, 3, 1]])
print(a)
b = torch.Tensor([[0], [0]])
print(b)

tensor([[1., 1., 1.],
        [2., 3., 1.]])
tensor([[0.],
        [0.]])


In [9]:
torch.cat([a,b], 1)

tensor([[1., 1., 1., 0.],
        [2., 3., 1., 0.]])

In [10]:
threshold = torch.nn.Parameter(torch.Tensor([0.5]))
threshold

Parameter containing:
tensor([0.5000], requires_grad=True)

In [11]:
a/3 >= threshold

tensor([[False, False, False],
        [ True,  True, False]])

In [22]:
bestModel = ContextLNN(0.85, -1, False)
bestModel.load_state_dict(torch.load("checkpoint/best_model.pt"))
bestModel.eval()

ContextLNN(
  (sim_disjunction_or): or_lukasiewicz(
    (AND): and_lukasiewicz(
      (cdd): cdd_lnn()
    )
  )
  (predicate_and): and_lukasiewicz(
    (cdd): cdd_lnn()
  )
  (batch_norm): BatchNorm1d(6, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (batch_norm_cat): BatchNorm1d(3, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
)

In [30]:
class or_sum(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        # TODO: change this
        return torch.sum(x, 1, keepdim=True)


In [32]:
print(a)
or_sum()(a)

tensor([[1., 1., 1.],
        [2., 3., 1.]])


tensor([[3.],
        [6.]])

In [29]:
list(bestModel.parameters())

[Parameter containing:
 tensor([0.2000], requires_grad=True),
 Parameter containing:
 tensor([0.2500], requires_grad=True),
 Parameter containing:
 tensor([[0.1117]], requires_grad=True),
 Parameter containing:
 tensor([[ 1.7367, -0.3614,  0.5991,  0.3991,  0.0964,  1.1870]],
        requires_grad=True),
 Parameter containing:
 tensor([[0.0428]], requires_grad=True),
 Parameter containing:
 tensor([[-1.6838, -2.6671, -1.8335, -1.6172]], requires_grad=True),
 Parameter containing:
 tensor([-0.2487, -0.1358, -0.3617,  0.2377,  1.2439,  0.7895],
        requires_grad=True),
 Parameter containing:
 tensor([-0.9395, -0.7981, -0.6839, -0.8211,  0.3392,  0.2754],
        requires_grad=True),
 Parameter containing:
 tensor([0.8534, 0.0187, 0.2231], requires_grad=True),
 Parameter containing:
 tensor([-0.5101, -0.5262, -0.4510], requires_grad=True)]

In [41]:
preds = [[('http://dbpedia.org/resource/U.S._state', 2.122520923614502), ('http://dbpedia.org/resource/United_States', 1.9040855169296265), ('http://dbpedia.org/resource/United_States_Census_Bureau', 1.2175928354263306), ('http://dbpedia.org/resource/United_States_Navy', 1.1561580896377563), ('http://dbpedia.org/resource/Georgia_(U.S._state)', 1.1186010837554932)], [('http://dbpedia.org/resource/United_States', 6.0), ('http://dbpedia.org/resource/United_States_Navy', 3.022167205810547), ('http://dbpedia.org/resource/United_States_Army', 2.7872660160064697), ('http://dbpedia.org/resource/United_States_Senate', 2.6330716609954834), ('http://dbpedia.org/resource/United_States_Census_Bureau', 2.4424610137939453)], [('http://dbpedia.org/resource/Lincolnshire', 2.5069339275360107), ('http://dbpedia.org/resource/Abraham_Lincoln', 2.163151979446411), ('http://dbpedia.org/resource/Lincoln_City_F.C.', 2.0932846069335938), ('http://dbpedia.org/resource/Lincoln_Near-Earth_Asteroid_Research', 1.9766583442687988), ('http://dbpedia.org/resource/Lincoln,_England', 1.7709510326385498)]]

In [42]:
preds

[[('http://dbpedia.org/resource/U.S._state', 2.122520923614502),
  ('http://dbpedia.org/resource/United_States', 1.9040855169296265),
  ('http://dbpedia.org/resource/United_States_Census_Bureau',
   1.2175928354263306),
  ('http://dbpedia.org/resource/United_States_Navy', 1.1561580896377563),
  ('http://dbpedia.org/resource/Georgia_(U.S._state)', 1.1186010837554932)],
 [('http://dbpedia.org/resource/United_States', 6.0),
  ('http://dbpedia.org/resource/United_States_Navy', 3.022167205810547),
  ('http://dbpedia.org/resource/United_States_Army', 2.7872660160064697),
  ('http://dbpedia.org/resource/United_States_Senate', 2.6330716609954834),
  ('http://dbpedia.org/resource/United_States_Census_Bureau',
   2.4424610137939453)],
 [('http://dbpedia.org/resource/Lincolnshire', 2.5069339275360107),
  ('http://dbpedia.org/resource/Abraham_Lincoln', 2.163151979446411),
  ('http://dbpedia.org/resource/Lincoln_City_F.C.', 2.0932846069335938),
  ('http://dbpedia.org/resource/Lincoln_Near-Earth_Ast

In [43]:
gold = [[[('http://dbpedia.org/resource/United_States', 5.999999999999999), ('http://dbpedia.org/resource/United_States_Navy', 3.0221670864000245), ('http://dbpedia.org/resource/United_States_Army', 2.787266198066909), ('http://dbpedia.org/resource/United_States_Senate', 2.633071769823949), ('http://dbpedia.org/resource/United_States_Census_Bureau', 2.44246074269411)]], [[('http://dbpedia.org/resource/Lincolnshire', 2.5069341912486776), ('http://dbpedia.org/resource/Abraham_Lincoln', 2.1631519342356977), ('http://dbpedia.org/resource/Lincoln_City_F.C.', 2.0932846530592344), ('http://dbpedia.org/resource/Lincoln_Near-Earth_Asteroid_Research', 1.9766583104509454), ('http://dbpedia.org/resource/Lincoln,_England', 1.7709509522581537)]]]
gold

[[[('http://dbpedia.org/resource/United_States', 5.999999999999999),
   ('http://dbpedia.org/resource/United_States_Navy', 3.0221670864000245),
   ('http://dbpedia.org/resource/United_States_Army', 2.787266198066909),
   ('http://dbpedia.org/resource/United_States_Senate', 2.633071769823949),
   ('http://dbpedia.org/resource/United_States_Census_Bureau',
    2.44246074269411)]],
 [[('http://dbpedia.org/resource/Lincolnshire', 2.5069341912486776),
   ('http://dbpedia.org/resource/Abraham_Lincoln', 2.1631519342356977),
   ('http://dbpedia.org/resource/Lincoln_City_F.C.', 2.0932846530592344),
   ('http://dbpedia.org/resource/Lincoln_Near-Earth_Asteroid_Research',
    1.9766583104509454),
   ('http://dbpedia.org/resource/Lincoln,_England', 1.7709509522581537)]]]

In [21]:
df_train_val = pd.read_csv(args.train_data)
df_test = pd.read_csv(args.test_data)

# train
features_train_val = np.array(
    [np.fromstring(s[1:-1], dtype=np.float, sep=', ') for s in df_train_val.Features.values])
X_train_val = torch.from_numpy(features_train_val).float()
Y_train_val = torch.from_numpy(df_train_val.Label.values).float()
mention_labels_train_val = df_train_val.Mention_label.values
questions_train_val = df_train_val.Question.values
x_train, x_val, y_train, y_val, m_labels_train, m_labels_val, ques_train, ques_val = \
    train_test_split(X_train_val, Y_train_val, mention_labels_train_val, questions_train_val,
                     test_size=0.2, train_size=0.8, random_state=100)

# test
features_test = np.array([np.fromstring(s[1:-1], dtype=np.float, sep=', ') for s in df_test.Features.values])
x_test = torch.from_numpy(features_test).float()
y_test = torch.from_numpy(df_test.Label.values).float()
m_labels_test = df_test.Mention_label.values


In [6]:
len(set(df_test.Question.values))
df_test.head()

Unnamed: 0                                     Question  \
0           0  Who was the wife of U.S. president Lincoln?   
1           1  Who was the wife of U.S. president Lincoln?   
2           2  Who was the wife of U.S. president Lincoln?   
3           3  Who was the wife of U.S. president Lincoln?   
4           4  Who was the wife of U.S. president Lincoln?   

                               Mention_label  \
0                         U.S.;United States   
1  U.S.;National Register of Historic Places   
2           U.S.;United States Census Bureau   
3                U.S.;Hispanic (U.S. Census)   
4                    U.S.;United States Navy   

                                            Features  Label  
0  [0.5961538553237915, 0.0, 0.15384615384615385,...      0  
1  [0.42592594027519226, 0.0, 0.02777777777777779...      0  
2  [0.5722222328186035, 0.0, 0.07407407407407407,...      0  
3  [0.6439393758773804, 0.0, 0.18181818181818177,...      0  
4  [0.5833333134651184, 0.0, 0.11111111111111116,...      0

In [74]:
def pick_model(model_name, alpha):
    if model_name == "purename":
        return PureNameLNN(alpha, 2, False)
    elif model_name == "context":
        return ContextLNN(alpha, 2, False)
    elif model_name == "complex":
        return ComplexRuleLNN(alpha, 2, False)
    else:
        print("WRONG name input")
        return None


def get_qald_metrics(val_pred, val_y, val_m_labels, ques_val):
    """val_pred are 0/1 s after applying a threshold"""
    rows = []
    question_rows_map = defaultdict(list)

    for i, pred in enumerate(val_pred):
        pred = pred.data.tolist()[0]
        if pred:
            men_entity_label = '_'.join(val_m_labels[i].split(';')[-1].split())
            question_rows_map[ques_val[i]].append(('http://dbpedia.org/resource/{}'.format(men_entity_label), 1.0))
#             print(ques_val[i], question_rows_map[ques_val[i]])

    for key, value in question_rows_map.items():
        rows.append([key, [value]])

    df_output = pd.DataFrame(rows, columns=['Question', 'Entities'])
    df_output['Classes'] = str([])
    df_output.head()
    
    # gold 
    benchmark = pd.read_csv('../../../data/gt_sparql.csv')
    benchmark = benchmark.set_index('Question')
    benchmark = benchmark.replace(np.nan, '', regex=True)
    benchmark['Entities'] = benchmark['Entities'].astype(object)
    is_qald_gt = True
    
    # pred 
    predictions = df_output
    predictions = predictions.set_index('Question')
    predictions['Entities'] = predictions['Entities']
    predictions['Classes'] = predictions['Classes']

    metrics = compute_metrics(benchmark=benchmark, predictions=predictions, limit=410, is_qald_gt=is_qald_gt, eval='full')

    scores = metrics['macro']['named']
    prec, recall, f1 = scores['precision'], scores['recall'], scores['f1']
    print(prec, recall, f1)
    return prec, recall, f1


def evaluate(eval_model, x_eval, y_eval, m_labels_eval, ques_eval, loss_fn, threshold=0.5):
    """evaluate a model on validation data"""
    eval_model.eval()
    with torch.no_grad():
        val_pred = eval_model(x_eval, m_labels_eval)
        loss = loss_fn(val_pred, y_eval)
        val_pred_ = val_pred > threshold
        print("val loss", loss)
        prec, recall, f1 = get_qald_metrics(val_pred_, y_eval, m_labels_eval, ques_eval)
#         prec, recall, f1, _ = precision_recall_fscore_support(y_eval, val_pred_, average='macro')
        print("f1 is {} w/ threshold {} ".format(f1, threshold))
#     return loss, f1, val_pred

    
    return loss, f1, val_pred

In [75]:
model = pick_model(args.model_name, args.alpha)
loss_fn = nn.BCELoss()
loss, f1, val_pred = evaluate(model, x_val, y_val, m_labels_val, ques_val, loss_fn)

val loss tensor(0.0571)
0.4792 0.5417 0.5085
f1 is 0.5085 w/ threshold 0.5 


In [77]:
best_pred = val_pred
best_val_f1, best_val_loss = 0, 1000
best_tuned_threshold = 0.5
best_tuned_f1 = best_val_f1
for threshold_ in np.linspace(0.99, 1.0, num=100):
    y_val_preds = best_pred >= threshold_
    prec, recall, f1 = get_qald_metrics(y_val_preds, y_val, m_labels_val, ques_val)
    if f1 > best_tuned_f1:
        best_tuned_threshold = threshold_
        best_tuned_f1 = f1
print("Val -- After tuning, the best f1 is {} w/ threshold {}".format(best_tuned_f1, best_tuned_threshold))

0.5 0.5652 0.5306
0.5 0.5652 0.5306
0.5 0.5652 0.5306
0.5 0.5652 0.5306
0.5 0.5652 0.5306
0.5 0.5652 0.5306
0.5 0.5652 0.5306
0.5 0.5652 0.5306
0.5 0.5652 0.5306
0.5 0.5652 0.5306
0.5 0.5652 0.5306
0.5 0.5652 0.5306
0.5 0.5652 0.5306
0.5 0.5652 0.5306
0.5 0.5652 0.5306
0.5 0.5652 0.5306
0.5 0.5652 0.5306
0.5 0.5652 0.5306
0.5 0.5652 0.5306
0.5 0.5652 0.5306
0.5 0.5652 0.5306
0.5 0.5652 0.5306
0.5 0.5652 0.5306
0.5 0.5652 0.5306
0.5 0.5652 0.5306
0.5 0.5652 0.5306
0.5 0.5652 0.5306
0.5 0.5652 0.5306
0.5 0.5652 0.5306
0.5 0.5652 0.5306
0.5 0.5652 0.5306
0.5 0.5652 0.5306
0.5 0.5652 0.5306
0.5 0.5652 0.5306
0.5 0.5652 0.5306
0.5 0.5652 0.5306
0.5111 0.5778 0.5424
0.5111 0.5778 0.5424
0.5111 0.5778 0.5424
0.5111 0.5778 0.5424
0.5111 0.5778 0.5424
0.5111 0.5778 0.5424
0.5111 0.5778 0.5424
0.5111 0.5778 0.5424
0.5111 0.5778 0.5424
0.5111 0.5778 0.5424
0.5111 0.5778 0.5424
0.5111 0.5778 0.5424
0.5111 0.5778 0.5424
0.5111 0.5778 0.5424
0.5111 0.5778 0.5424
0.5111 0.5778 0.5424
0.5111 0.5778 0.

In [66]:
ques_test = df_test.Question

evaluate(model, x_test, y_test, m_labels_test, ques_test, loss_fn, threshold=.9994949494949495)

val loss tensor(0.0524)
0.8058 0.7326 0.7674
f1 is 0.7674 w/ threshold 0.9994949494949495 


(tensor(0.0524),
 0.7674,
 tensor([[9.9950e-01],
         [5.2919e-14],
         [2.0628e-04],
         ...,
         [2.0741e-10],
         [5.3063e-20],
         [2.0741e-10]]))

In [ ]:
# train model and evaluate
# print(model(x_train, m_labels_train))
# best_tuned_threshold = train(model, x_train, y_train, m_labels_train, ques_train, x_val, y_val, m_labels_val, ques_val, args.checkpoint_name, args.num_epoch)
# test_pred = test(x_test, y_test, m_labels_test, best_tuned_threshold, args.alpha, args.checkpoint_name, args.model_name)
# write_output(df_test, m_labels_test, test_pred, args.output_file_name)

# print(args.use_binary)

In [4]:
import sys
sys.path.append('../../../')

In [5]:
from el_evaluation import *

In [15]:
gold_file_path = '../../../data/gt_sparql.csv'
prediction_file = 'output/purename_nway_alpha095.csv' 


In [32]:
def eval(gold_file_path, prediction_file):
    
    # gold 
    benchmark = pd.read_csv(gold_file_path)
    benchmark = benchmark.set_index('Question')
    benchmark = benchmark.replace(np.nan, '', regex=True)
    benchmark['Entities'] = benchmark['Entities'].astype(object)
    is_qald_gt = True
    
    # pred 
    predictions = pd.read_csv(prediction_file)
    predictions = predictions.set_index('Question')
    predictions['Entities'] = predictions['Entities']
    predictions['Classes'] = predictions['Classes']

    metrics = compute_metrics(benchmark=benchmark, predictions=predictions, limit=410, is_qald_gt=is_qald_gt, eval='full')

    scores = metrics['macro']['named']
    prec, recall, f1 = scores['precision'], scores['recall'], scores['f1']
    print(prec, recall, f1)
    return prec, recall, f1

In [33]:

import glob, os
import pandas as pd

rows = []
columns = ['filename', 'alpha', 'precision', 'recall', 'f1']
for prediction_file in sorted(glob.glob("output/*.csv")):
    print("=====", prediction_file,"=====")
    prec, rec, f1 = eval(gold_file_path, prediction_file)
    filename = prediction_file.split('/')[-1][:-4]
    alpha = filename[-2:]
    print(filename, alpha, prec, rec, f1)
    rows.append([filename, alpha, prec, rec, f1])
df = pd.DataFrame(rows, columns=columns)
df.to_csv('eval_results.csv')

===== output/complex_binary_alpha085.csv =====


NameError: name 'gold_file_path' is not defined