In [1]:
import torch

In [21]:
a = torch.rand((4, 5))
a

tensor([[0.2715, 0.0164, 0.9672, 0.2272, 0.4178],
        [0.7011, 0.0044, 0.5754, 0.7451, 0.1037],
        [0.7430, 0.2073, 0.0167, 0.6639, 0.0560],
        [0.3903, 0.7431, 0.3068, 0.7702, 0.8946]])

In [18]:
a > 0.2

tensor([[ True,  True, False,  True, False],
        [ True,  True,  True,  True,  True],
        [ True, False, False, False,  True],
        [ True,  True, False,  True,  True]])

In [19]:
a > torch.Tensor([0.7, 0.9, 0.1, 0.2, 0.2])

tensor([[False, False,  True,  True, False],
        [False, False,  True,  True,  True],
        [ True, False,  True, False,  True],
        [False, False, False,  True,  True]])

In [20]:
a * torch.Tensor([1, 0, 1, 0, 1])

tensor([[6.8726e-01, 0.0000e+00, 1.1499e-01, 0.0000e+00, 1.2892e-04],
        [5.7696e-01, 0.0000e+00, 3.8653e-01, 0.0000e+00, 6.8048e-01],
        [9.4968e-01, 0.0000e+00, 1.0972e-01, 0.0000e+00, 9.9686e-01],
        [3.6701e-01, 0.0000e+00, 6.1057e-02, 0.0000e+00, 5.6744e-01]])

In [24]:
a[:, [3, 0, 1, 2]]

tensor([[0.2272, 0.2715, 0.0164, 0.9672],
        [0.7451, 0.7011, 0.0044, 0.5754],
        [0.6639, 0.7430, 0.2073, 0.0167],
        [0.7702, 0.3903, 0.7431, 0.3068]])

In [28]:
import numpy as np
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])