In [1]:
import torch

In [16]:
from RuleLNN_nway_sigmoid_vec_type import *
from run_el_kfolds_type import *

In [18]:
bestModel = ComplexRuleLNN(0.9, -1, False)
bestModel.load_state_dict(torch.load("checkpoint/best_model_exp_type_sigmoid_without_missing_0812.pt"))
bestModel.eval()

ComplexRuleLNN(
  (pureNameRule): PureNameLNN(
    (sim_disjunction_or): or_lukasiewicz(
      (AND): and_lukasiewicz(
        (cdd): cdd_lnn()
      )
    )
    (predicate_and): and_lukasiewicz(
      (cdd): cdd_lnn()
    )
  )
  (contextRule): ContextLNN(
    (sim_disjunction_or): or_lukasiewicz(
      (AND): and_lukasiewicz(
        (cdd): cdd_lnn()
      )
    )
    (predicate_and): and_lukasiewicz(
      (cdd): cdd_lnn()
    )
  )
  (typeRule): TypeLNN(
    (sim_disjunction_or): or_lukasiewicz(
      (AND): and_lukasiewicz(
        (cdd): cdd_lnn()
      )
    )
    (predicate_and): and_lukasiewicz(
      (cdd): cdd_lnn()
    )
  )
  (rule_or): or_lukasiewicz(
    (AND): and_lukasiewicz(
      (cdd): cdd_lnn()
    )
  )
)

In [24]:
torch.Tensor(bestModel.pureNameRule.threshold)

tensor([[0.1601, 1.2779, 0.5638, 1.0359]], grad_fn=<SliceBackward>)

In [19]:
for name, param in bestModel.named_parameters():
    if param.requires_grad:
        print(name, 'param -- data', param.data, 'grad -- ', param.grad)

pureNameRule.threshold param -- data tensor([[0.1601, 1.2779, 0.5638, 1.0359]]) grad --  None
pureNameRule.sim_disjunction_or.AND.param_arg_weights param -- data tensor([0.5974, 0.0887, 0.8354, 0.2982]) grad --  None
pureNameRule.sim_disjunction_or.AND.param_beta param -- data tensor([1.1263]) grad --  None
pureNameRule.sim_disjunction_or.AND.cdd.gamma param -- data tensor([[0.0476]]) grad --  None
pureNameRule.sim_disjunction_or.AND.cdd.mu param -- data tensor([[0.8161, 0.7388, 0.8360, 0.9715, 0.2425]]) grad --  None
pureNameRule.predicate_and.param_arg_weights param -- data tensor([0.3233, 0.6116]) grad --  None
pureNameRule.predicate_and.param_beta param -- data tensor([0.6658]) grad --  None
pureNameRule.predicate_and.cdd.gamma param -- data tensor([[0.3366]]) grad --  None
pureNameRule.predicate_and.cdd.mu param -- data tensor([[0.7287, 0.4567, 0.5808]]) grad --  None
contextRule.threshold param -- data tensor([ 0.0206,  0.6210, -0.0859,  0.4089]) grad --  None
contextRule.context

In [ ]:
## Thresholds 

In [33]:
torch.sigmoid(torch.Tensor([0.5]))

tensor([0.6225])

In [12]:
torch.sigmoid(torch.Tensor([0.2]))

tensor([0.5498])

In [13]:
torch.sigmoid(torch.Tensor([0.25]))

tensor([0.5622])

## PureName

In [46]:
print(">> PureName: ", torch.sigmoid(torch.Tensor(bestModel.pureNameRule.threshold)))
print(">> PureName weights: ", torch.relu(torch.Tensor(bestModel.pureNameRule.sim_disjunction_or.AND.param_arg_weights)))
print(">> PureName: ", torch.Tensor(bestModel.pureNameRule.sim_disjunction_or.AND.param_beta))
print(">> PureName weights: ", torch.relu(torch.Tensor(bestModel.pureNameRule.predicate_and.param_arg_weights)))
print(">> PureName: ", torch.Tensor(bestModel.pureNameRule.predicate_and.param_beta))

>> PureName:  tensor([[0.5399, 0.7821, 0.6373, 0.7381]], grad_fn=<SigmoidBackward>)
>> PureName weights:  tensor([0.5974, 0.0887, 0.8354, 0.2982], grad_fn=<ReluBackward0>)
>> PureName:  tensor([1.1263], grad_fn=<SliceBackward>)
>> PureName weights:  tensor([0.3233, 0.6116], grad_fn=<ReluBackward0>)
>> PureName:  tensor([0.6658], grad_fn=<SliceBackward>)


## Context

In [47]:
print(">> Context: ", torch.sigmoid(torch.Tensor(bestModel.contextRule.threshold)))
print(">> Context: ", torch.sigmoid(torch.Tensor(bestModel.contextRule.context_threshold)))
print(">> Context weights: ", torch.relu(torch.Tensor(bestModel.contextRule.sim_disjunction_or.AND.param_arg_weights)))
print(">> Context: ", torch.Tensor(bestModel.contextRule.sim_disjunction_or.AND.param_beta))
print(">> Context weights: ", torch.relu(torch.Tensor(bestModel.contextRule.predicate_and.param_arg_weights)))
print(">> Context: ", torch.Tensor(bestModel.contextRule.predicate_and.param_beta))

>> Context:  tensor([0.5051, 0.6504, 0.4785, 0.6008], grad_fn=<SigmoidBackward>)
>> Context:  tensor([0.4268], grad_fn=<SigmoidBackward>)
>> Context weights:  tensor([0.5836, 0.0000, 0.7990, 0.0000], grad_fn=<ReluBackward0>)
>> Context:  tensor([0.5419], grad_fn=<SliceBackward>)
>> Context weights:  tensor([0.4798, 0.2068, 0.5386], grad_fn=<ReluBackward0>)
>> Context:  tensor([0.8145], grad_fn=<SliceBackward>)


## Type

In [48]:
print(">> Type: ", torch.sigmoid(torch.Tensor(bestModel.typeRule.threshold)))
print(">> Type: ", torch.sigmoid(torch.Tensor(bestModel.typeRule.type_features_threshold)))
print(">> Type weights: ", torch.relu(torch.Tensor(bestModel.typeRule.sim_disjunction_or.AND.param_arg_weights)))
print(">> Type: ", torch.Tensor(bestModel.typeRule.sim_disjunction_or.AND.param_beta))
print(">> Type weights: ", torch.relu(torch.Tensor(bestModel.typeRule.predicate_and.param_arg_weights)))
print(">> Type: ", torch.Tensor(bestModel.typeRule.predicate_and.param_beta))

>> Type:  tensor([0.5672, 0.6827, 0.5995, 0.7025], grad_fn=<SigmoidBackward>)
>> Type:  tensor([0.4732], grad_fn=<SigmoidBackward>)
>> Type weights:  tensor([0.6348, 0.0000, 0.4998, 0.1009], grad_fn=<ReluBackward0>)
>> Type:  tensor([0.4344], grad_fn=<SliceBackward>)
>> Type weights:  tensor([0.8886, 1.0972, 0.6595], grad_fn=<ReluBackward0>)
>> Type:  tensor([0.7409], grad_fn=<SliceBackward>)


## Complex

In [51]:
print(">> Complex: ", torch.relu(torch.Tensor(bestModel.rule_or.AND.param_arg_weights)))
print(">> Type: ", torch.sigmoid(torch.Tensor(bestModel.rule_or.AND.param_beta)))

>> Complex:  tensor([1.3364, 1.4012, 1.4915], grad_fn=<ReluBackward0>)
>> Type:  tensor([0.7472], grad_fn=<SigmoidBackward>)


In [25]:
# purename
torch.sigmoid(torch.Tensor(bestModel.pureNameRule.threshold))

tensor([[0.5399, 0.7821, 0.6373, 0.7381]], grad_fn=<SigmoidBackward>)

In [5]:
# context
torch.sigmoid(torch.Tensor([0.3928,  0.4885, -0.2478,  0.3990]))

tensor([0.5970, 0.6198, 0.4384, 0.5984])

In [6]:
# context
torch.sigmoid(torch.Tensor([-0.4180]))

tensor([0.3970])

In [ ]:
## Weights

In [8]:
# purename OR
torch.relu(torch.Tensor([ 1.2147,  0.2402,  0.2379, -0.0016]))

tensor([1.2147, 0.2402, 0.2379, 0.0000])

In [9]:
# purename AND 
torch.relu(torch.Tensor([0.7952, 0.7334]))

tensor([0.7952, 0.7334])

In [10]:
# context OR
torch.relu(torch.Tensor([-9.2569e-04, -9.5747e-05,  1.2711e+00, -6.0086e-04]))

tensor([0.0000, 0.0000, 1.2711, 0.0000])

In [11]:
# context AND 
torch.relu(torch.Tensor([0.1549, 1.4567, 0.6724]))

tensor([0.1549, 1.4567, 0.6724])